# SPDX-License-Identifier: GPL-2.0-only
#
# Samsung thermal specific Makefile
#
obj-$(CONFIG_EXYNOS_THERMAL)			+= exynos_thermal.o
exynos_thermal-y				:= exynos_tmu.o
obj-$(CONFIG_GS201_ACPM_THERMAL)		+= gs201_acpm_thermal.o
