# SPDX-License-Identifier: GPL-2.0
#
# Google SoC drivers ported from AOSP private/google-modules/soc/gs/.

obj-$(CONFIG_EXYNOS_PMU_IF)	+= exynos-pmu-if.o
obj-$(CONFIG_EXYNOS_PM_QOS)	+= exynos_pm_qos.o
obj-$(CONFIG_EXYNOS_CPUPM)	+= exynos-cpupm.o
